export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_LOADED = 'USER_LOADED,';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';

export const CREATE_PROFILE_SUCCESS = 'CREATE_SUCCESS';
export const CREATE_PROFILE_ERROR = 'CREATE_ERROR';

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const GET_EMPLOYEE_LIST = 'GET_EMPLOYEES_LIST';
export const GET_EMPLOYEE_LIST_FAILED = 'GET_EMPLOYEES_LIST_FAILED';

export const GET_EMPLOYEE_PROFILE = 'GET_EMPLOYEE_PROFILE';
export const GET_EMPLOYEE_PROFILE_ERROR = 'GET_EMPLOYEE_PROFILE_ERROR';

export const DELETE_EMPLOYEE_PROFILE = 'DELETE_EMPLOYEE_PROFILE';
export const DELETE_EMPLOYEE_PROFILE_FAILED = 'DELETE_EMPLOYEE_PROFILE_FAILED';

export const CREATE_ROLE = 'CREATE_ROLE';
export const DELETE_ROLE = 'DELETE_ROLE';

export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const LOGOUT = 'LOGOUT';
